-- =====================================================
-- TABELA 1: product_types
-- Armazena tipos de produtos INSULFILM e PPF
-- =====================================================

CREATE TABLE public.product_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL CHECK (category IN ('INSULFILM', 'PPF')),
  brand text NOT NULL,
  name text NOT NULL,
  model text,
  light_transmission text,
  description text,
  unit_price numeric DEFAULT 0,
  cost_per_meter numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  company_id bigint NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE
);

-- Índices
CREATE INDEX idx_product_types_category ON public.product_types(category);
CREATE INDEX idx_product_types_company ON public.product_types(company_id);

-- RLS
ALTER TABLE public.product_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view product_types from their company"
  ON public.product_types FOR SELECT
  USING (company_id = get_user_company_id(auth.uid()));

CREATE POLICY "Users can manage product_types from their company"
  ON public.product_types FOR ALL
  USING (company_id = get_user_company_id(auth.uid()))
  WITH CHECK (company_id = get_user_company_id(auth.uid()));

-- Trigger para updated_at
CREATE TRIGGER update_product_types_updated_at
  BEFORE UPDATE ON public.product_types
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- =====================================================
-- TABELA 2: vehicle_regions
-- Armazena regiões do veículo para aplicação
-- =====================================================

CREATE TABLE public.vehicle_regions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL CHECK (category IN ('INSULFILM', 'PPF')),
  name text NOT NULL,
  description text,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  company_id bigint NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE
);

-- Índices
CREATE INDEX idx_vehicle_regions_category ON public.vehicle_regions(category);
CREATE INDEX idx_vehicle_regions_company ON public.vehicle_regions(company_id);

-- RLS
ALTER TABLE public.vehicle_regions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view vehicle_regions from their company"
  ON public.vehicle_regions FOR SELECT
  USING (company_id = get_user_company_id(auth.uid()));

CREATE POLICY "Users can manage vehicle_regions from their company"
  ON public.vehicle_regions FOR ALL
  USING (company_id = get_user_company_id(auth.uid()))
  WITH CHECK (company_id = get_user_company_id(auth.uid()));

-- =====================================================
-- TABELA 3: region_consumption_rules
-- Regras de consumo por região e tamanho
-- =====================================================

CREATE TABLE public.region_consumption_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category text NOT NULL CHECK (category IN ('INSULFILM', 'PPF')),
  region_id bigint NOT NULL REFERENCES public.vehicle_regions(id) ON DELETE CASCADE,
  vehicle_size text NOT NULL CHECK (vehicle_size IN ('P', 'M', 'G')),
  meters_consumed numeric NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  company_id bigint NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  UNIQUE(region_id, vehicle_size, company_id)
);

-- Índices
CREATE INDEX idx_region_consumption_category ON public.region_consumption_rules(category);
CREATE INDEX idx_region_consumption_region ON public.region_consumption_rules(region_id);
CREATE INDEX idx_region_consumption_company ON public.region_consumption_rules(company_id);

-- RLS
ALTER TABLE public.region_consumption_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view consumption_rules from their company"
  ON public.region_consumption_rules FOR SELECT
  USING (company_id = get_user_company_id(auth.uid()));

CREATE POLICY "Users can manage consumption_rules from their company"
  ON public.region_consumption_rules FOR ALL
  USING (company_id = get_user_company_id(auth.uid()))
  WITH CHECK (company_id = get_user_company_id(auth.uid()));

-- Trigger para updated_at
CREATE TRIGGER update_region_consumption_rules_updated_at
  BEFORE UPDATE ON public.region_consumption_rules
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- =====================================================
-- TABELA 4: service_items_detailed
-- Itens detalhados de serviço para vendas
-- =====================================================

CREATE TABLE public.service_items_detailed (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id bigint NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
  category text NOT NULL CHECK (category IN ('INSULFILM', 'PPF')),
  product_type_id bigint NOT NULL REFERENCES public.product_types(id),
  region_id bigint NOT NULL REFERENCES public.vehicle_regions(id),
  meters_used numeric NOT NULL DEFAULT 0,
  unit_price numeric NOT NULL,
  total_price numeric NOT NULL,
  notes text,
  created_at timestamptz DEFAULT now(),
  company_id bigint NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE
);

-- Índices
CREATE INDEX idx_service_items_sale ON public.service_items_detailed(sale_id);
CREATE INDEX idx_service_items_product ON public.service_items_detailed(product_type_id);
CREATE INDEX idx_service_items_company ON public.service_items_detailed(company_id);

-- RLS
ALTER TABLE public.service_items_detailed ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view service_items from their company"
  ON public.service_items_detailed FOR SELECT
  USING (company_id = get_user_company_id(auth.uid()));

CREATE POLICY "Users can manage service_items from their company"
  ON public.service_items_detailed FOR ALL
  USING (company_id = get_user_company_id(auth.uid()))
  WITH CHECK (company_id = get_user_company_id(auth.uid()));

-- =====================================================
-- ATUALIZAÇÃO: Tabela materials
-- Adicionar coluna product_type_id
-- =====================================================

ALTER TABLE public.materials
  ADD COLUMN product_type_id bigint REFERENCES public.product_types(id) ON DELETE SET NULL;

CREATE INDEX idx_materials_product_type ON public.materials(product_type_id);