-- =====================================================
-- PIPELINE ESCALÁVEL + WHATSAPP INTEGRATION
-- =====================================================

-- 1. Tabela de Pipelines (quadros Kanban)
CREATE TABLE public.pipelines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Tabela de Definições de Estágios (colunas do Kanban)
CREATE TABLE public.pipeline_stage_definitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pipeline_id BIGINT REFERENCES public.pipelines(id) ON DELETE CASCADE,
  company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  position INTEGER DEFAULT 0,
  color TEXT DEFAULT '#3b82f6',
  is_final BOOLEAN DEFAULT false,
  is_won BOOLEAN DEFAULT false,
  is_lost BOOLEAN DEFAULT false,
  notify_client BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Tabela de Itens do Pipeline (cards)
CREATE TABLE public.pipeline_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pipeline_id BIGINT REFERENCES public.pipelines(id) ON DELETE CASCADE,
  stage_id BIGINT REFERENCES public.pipeline_stage_definitions(id) ON DELETE SET NULL,
  company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL DEFAULT 'deal',
  entity_id BIGINT,
  title TEXT NOT NULL,
  value NUMERIC,
  responsible_id UUID,
  client_id BIGINT REFERENCES public.clients(id) ON DELETE SET NULL,
  vehicle_id BIGINT REFERENCES public.vehicles(id) ON DELETE SET NULL,
  position INTEGER DEFAULT 0,
  is_urgent BOOLEAN DEFAULT false,
  scheduled_time TIME,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Tabela de Eventos do Pipeline (para orquestrador)
CREATE TABLE public.pipeline_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
  pipeline_id BIGINT REFERENCES public.pipelines(id) ON DELETE CASCADE,
  item_id BIGINT REFERENCES public.pipeline_items(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  from_stage_id BIGINT,
  to_stage_id BIGINT,
  user_id UUID,
  processed BOOLEAN DEFAULT false,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Tabela de Instâncias WhatsApp (conexões por empresa)
CREATE TABLE public.whatsapp_instances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE UNIQUE,
  instance_name TEXT NOT NULL,
  instance_id TEXT,
  api_key TEXT,
  status TEXT DEFAULT 'disconnected',
  phone_number TEXT,
  phone_name TEXT,
  qr_code TEXT,
  last_connected_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 6. Tabela de Mensagens WhatsApp
CREATE TABLE public.whatsapp_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES public.companies(id) ON DELETE CASCADE,
  instance_id BIGINT REFERENCES public.whatsapp_instances(id) ON DELETE SET NULL,
  channel TEXT DEFAULT 'whatsapp',
  to_phone TEXT NOT NULL,
  content TEXT NOT NULL,
  template_name TEXT,
  related_pipeline_item BIGINT REFERENCES public.pipeline_items(id) ON DELETE SET NULL,
  related_client_id BIGINT REFERENCES public.clients(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'pending',
  error_message TEXT,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- =====================================================
-- TRIGGERS
-- =====================================================

-- Trigger para gerar evento ao mover item de estágio
CREATE OR REPLACE FUNCTION public.fn_pipeline_item_moved()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.stage_id IS DISTINCT FROM NEW.stage_id THEN
    INSERT INTO public.pipeline_events (
      company_id,
      pipeline_id,
      item_id,
      event_type,
      from_stage_id,
      to_stage_id,
      user_id
    ) VALUES (
      NEW.company_id,
      NEW.pipeline_id,
      NEW.id,
      'item.moved',
      OLD.stage_id,
      NEW.stage_id,
      auth.uid()
    );
  END IF;
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE TRIGGER trg_pipeline_item_moved
AFTER UPDATE OF stage_id ON public.pipeline_items
FOR EACH ROW EXECUTE FUNCTION public.fn_pipeline_item_moved();

-- Trigger para updated_at em pipelines
CREATE TRIGGER update_pipelines_updated_at
BEFORE UPDATE ON public.pipelines
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Trigger para updated_at em whatsapp_instances
CREATE TRIGGER update_whatsapp_instances_updated_at
BEFORE UPDATE ON public.whatsapp_instances
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- =====================================================
-- RLS POLICIES
-- =====================================================

-- Pipelines
ALTER TABLE public.pipelines ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view pipelines from their company"
  ON public.pipelines FOR SELECT
  USING (company_id = get_user_company_id(auth.uid()));

CREATE POLICY "Admin can manage pipelines"
  ON public.pipelines FOR ALL
  USING (company_id = get_user_company_id(auth.uid()) 
         AND has_role(auth.uid(), 'ADMIN'));

-- Pipeline Stage Definitions
ALTER TABLE public.pipeline_stage_definitions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view stage definitions from their company"
  ON public.pipeline_stage_definitions FOR SELECT
  USING (company_id = get_user_company_id(auth.uid()));

CREATE POLICY "Admin can manage stage definitions"
  ON public.pipeline_stage_definitions FOR ALL
  USING (company_id = get_user_company_id(auth.uid()) 
         AND has_role(auth.uid(), 'ADMIN'));

-- Pipeline Items
ALTER TABLE public.pipeline_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view items from their company"
  ON public.pipeline_items FOR SELECT
  USING (company_id = get_user_company_id(auth.uid()) 
         AND has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'VENDEDOR'::app_role, 'PRODUCAO'::app_role]));

CREATE POLICY "Users can insert items in their company"
  ON public.pipeline_items FOR INSERT
  WITH CHECK (company_id = get_user_company_id(auth.uid()) 
              AND has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'VENDEDOR'::app_role, 'PRODUCAO'::app_role]));

CREATE POLICY "Users can update items in their company"
  ON public.pipeline_items FOR UPDATE
  USING (company_id = get_user_company_id(auth.uid()) 
         AND has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'VENDEDOR'::app_role, 'PRODUCAO'::app_role]));

CREATE POLICY "Admin can delete items"
  ON public.pipeline_items FOR DELETE
  USING (company_id = get_user_company_id(auth.uid()) 
         AND has_role(auth.uid(), 'ADMIN'));

-- Pipeline Events
ALTER TABLE public.pipeline_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view events from their company"
  ON public.pipeline_events FOR SELECT
  USING (company_id = get_user_company_id(auth.uid()));

CREATE POLICY "System can insert events"
  ON public.pipeline_events FOR INSERT
  WITH CHECK (company_id = get_user_company_id(auth.uid()));

-- WhatsApp Instances
ALTER TABLE public.whatsapp_instances ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view whatsapp instance from their company"
  ON public.whatsapp_instances FOR SELECT
  USING (company_id = get_user_company_id(auth.uid()));

CREATE POLICY "Admin can manage whatsapp instance"
  ON public.whatsapp_instances FOR ALL
  USING (company_id = get_user_company_id(auth.uid()) 
         AND has_role(auth.uid(), 'ADMIN'));

-- WhatsApp Messages
ALTER TABLE public.whatsapp_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view whatsapp messages from their company"
  ON public.whatsapp_messages FOR SELECT
  USING (company_id = get_user_company_id(auth.uid()) 
         AND has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'VENDEDOR'::app_role]));

CREATE POLICY "Users can insert whatsapp messages"
  ON public.whatsapp_messages FOR INSERT
  WITH CHECK (company_id = get_user_company_id(auth.uid()) 
              AND has_any_role(auth.uid(), ARRAY['ADMIN'::app_role, 'VENDEDOR'::app_role]));

-- =====================================================
-- INDEXES
-- =====================================================

CREATE INDEX idx_pipeline_items_pipeline ON public.pipeline_items(pipeline_id);
CREATE INDEX idx_pipeline_items_stage ON public.pipeline_items(stage_id);
CREATE INDEX idx_pipeline_items_company ON public.pipeline_items(company_id);
CREATE INDEX idx_pipeline_events_processed ON public.pipeline_events(processed) WHERE processed = false;
CREATE INDEX idx_whatsapp_messages_status ON public.whatsapp_messages(status) WHERE status = 'pending';