CREATE TABLE public.terms_acceptances (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  user_email text not null,
  user_name text not null,
  terms_version text not null default '1.0',
  accepted_at timestamptz not null default now(),
  ip_address text
);

ALTER TABLE public.terms_acceptances ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Master can view all acceptances"
  ON public.terms_acceptances FOR SELECT
  TO authenticated
  USING (
    auth.uid() IN (
      SELECT user_id FROM profiles WHERE email = 'hg.lavila@gmail.com'
    )
  );

CREATE POLICY "Users can insert own acceptance"
  ON public.terms_acceptances FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);